name: Shopify CLI Theme

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
      - uses: shopify/shopify-cli-action@v1
        with:
          auth-token: ${{ secrets.DEV_THEME_AUTH_TOKEN }}
	  command: 'login --store=equest-dev.myshopify.com --password=zN!zapNreDF4eC9'
          command: 'theme push --theme ${{ secrets.DEV_THEME_ID }}'
